'use client'

import { supabase } from '@/lib/supabase'
import { getStaticSchema } from '@/lib/tableSchemas'
import { useQuery } from '@tanstack/react-query'

export interface ColumnInfo {
  name: string
  type: 'text' | 'number' | 'boolean' | 'date' | 'datetime' | 'uuid' | 'json' | 'unknown'
  nullable: boolean
  isPrimaryKey: boolean
  isAutoGenerated: boolean
}

function inferType(value: unknown, key: string): ColumnInfo['type'] {
  if (key === 'id') return 'uuid'
  if (key.endsWith('_at')) return 'datetime'
  if (key.endsWith('_date') || key === 'date') return 'date'
  if (typeof value === 'boolean') return 'boolean'
  if (typeof value === 'number') return 'number'
  if (typeof value === 'string') {
    // UUID pattern
    if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value)) {
      return 'uuid'
    }
    // ISO date
    if (/^\d{4}-\d{2}-\d{2}T/.test(value)) return 'datetime'
    if (/^\d{4}-\d{2}-\d{2}$/.test(value)) return 'date'
    return 'text'
  }
  if (value !== null && typeof value === 'object') return 'json'
  return 'text'
}

async function fetchSchema(tableName: string): Promise<ColumnInfo[]> {
  const { data, error } = await supabase.from(tableName).select('*').limit(1)
  if (error) throw error

  // If no rows returned, fall back to the static schema registry.
  // This guarantees forms always show the correct fields for empty tables.
  if (!data || data.length === 0) {
    const staticSchema = getStaticSchema(tableName)
    if (staticSchema.length > 0) return staticSchema
    // Ultimate fallback for truly unknown tables
    return [
      { name: 'id', type: 'uuid', nullable: false, isPrimaryKey: true, isAutoGenerated: true },
      { name: 'created_at', type: 'datetime', nullable: true, isPrimaryKey: false, isAutoGenerated: true },
    ]
  }

  const row = data[0] as Record<string, unknown>

  // Special case: gemini_usage_log uses integer id, not uuid
  if (tableName === 'gemini_usage_log') {
    const staticSchema = getStaticSchema(tableName)
    if (staticSchema.length > 0) return staticSchema
  }

  return Object.entries(row).map(([key, value]) => {
    const type = inferType(value, key)
    const isPrimaryKey = key === 'id'
    const isAutoGenerated = isPrimaryKey || key === 'created_at'
    return {
      name: key,
      type,
      nullable: value === null,
      isPrimaryKey,
      isAutoGenerated,
    }
  })
}

export function useSupabaseSchema(tableName: string) {
  return useQuery({
    queryKey: ['schema', tableName],
    queryFn: () => fetchSchema(tableName),
    staleTime: 5 * 60 * 1000, // 5 min — schema doesn't change often
    enabled: !!tableName,
  })
}
