/**
 * Static per-table column schema registry.
 *
 * This is used as the authoritative fallback when useSupabaseSchema cannot
 * infer columns from a live row (e.g. the table is empty).
 *
 * Derived from src/types/database.ts and verified against the live Supabase DB.
 */

import type { ColumnInfo } from '@/hooks/useSupabaseSchema'

type StaticSchema = Record<string, ColumnInfo[]>

export const TABLE_SCHEMAS: StaticSchema = {
  chatbot_leads: [
    { name: 'id',         type: 'uuid',     nullable: false, isPrimaryKey: true,  isAutoGenerated: true  },
    { name: 'name',       type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'phone',      type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'email',      type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'service',    type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'source',     type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'status',     type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'notes',      type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'created_at', type: 'datetime', nullable: true,  isPrimaryKey: false, isAutoGenerated: true  },
  ],
  appointments: [
    { name: 'id',         type: 'uuid',     nullable: false, isPrimaryKey: true,  isAutoGenerated: true  },
    { name: 'lead_id',    type: 'uuid',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'name',       type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'date',       type: 'date',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'time',       type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'status',     type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'notes',      type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'created_at', type: 'datetime', nullable: true,  isPrimaryKey: false, isAutoGenerated: true  },
  ],
  estimates: [
    { name: 'id',           type: 'uuid',     nullable: false, isPrimaryKey: true,  isAutoGenerated: true  },
    { name: 'client_name',  type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'client_email', type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'service_type', type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'amount',       type: 'number',   nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'status',       type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'notes',        type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'created_at',   type: 'datetime', nullable: true,  isPrimaryKey: false, isAutoGenerated: true  },
  ],
  gallery: [
    { name: 'id',          type: 'uuid',     nullable: false, isPrimaryKey: true,  isAutoGenerated: true  },
    { name: 'image_url',   type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'title',       type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'description', type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'created_at',  type: 'datetime', nullable: true,  isPrimaryKey: false, isAutoGenerated: true  },
  ],
  gemini_usage_log: [
    { name: 'id',          type: 'number',   nullable: false, isPrimaryKey: true,  isAutoGenerated: true  },
    { name: 'prompt',      type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'response',    type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'tokens_used', type: 'number',   nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'created_at',  type: 'datetime', nullable: true,  isPrimaryKey: false, isAutoGenerated: true  },
  ],
  profiles: [
    { name: 'id',         type: 'uuid',     nullable: false, isPrimaryKey: true,  isAutoGenerated: false },
    { name: 'name',       type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'role',       type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'avatar_url', type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'created_at', type: 'datetime', nullable: true,  isPrimaryKey: false, isAutoGenerated: true  },
  ],
  reviews: [
    { name: 'id',         type: 'uuid',     nullable: false, isPrimaryKey: true,  isAutoGenerated: true  },
    { name: 'author',     type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'rating',     type: 'number',   nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'content',    type: 'text',     nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'visible',    type: 'boolean',  nullable: true,  isPrimaryKey: false, isAutoGenerated: false },
    { name: 'created_at', type: 'datetime', nullable: true,  isPrimaryKey: false, isAutoGenerated: true  },
  ],
}

/** Returns the static schema for a table, or an empty array if unknown. */
export function getStaticSchema(tableName: string): ColumnInfo[] {
  return TABLE_SCHEMAS[tableName] ?? []
}
