'use client'

import { Sheet } from '@/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Switch } from '@/components/ui/switch'
import type { ColumnInfo } from '@/hooks/useSupabaseSchema'
import { cn } from '@/lib/utils'
import { zodResolver } from '@hookform/resolvers/zod'
import { Controller, useForm } from 'react-hook-form'
import { z } from 'zod'

interface AutoFormProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  schema: ColumnInfo[]
  defaultValues?: Record<string, unknown>
  onSubmit: (data: Record<string, unknown>) => Promise<void>
  mode: 'create' | 'edit'
  tableName: string
  isLoading?: boolean
  /** Optional enum options per column name */
  enumOptions?: Record<string, string[]>
}

function buildZodSchema(schema: ColumnInfo[]) {
  const shape: Record<string, z.ZodTypeAny> = {}
  for (const col of schema) {
    if (col.isAutoGenerated) continue
    let field: z.ZodTypeAny
    switch (col.type) {
      case 'number':
        field = z.coerce.number()
        break
      case 'boolean':
        field = z.boolean().optional().default(false)
        break
      case 'date':
      case 'datetime':
        field = z.string().optional()
        break
      case 'uuid':
        field = z
          .string()
          .regex(
            /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
            'Must be a valid UUID'
          )
          .optional()
          .or(z.literal(''))
        break
      default:
        if (col.name === 'email') {
          field = z.string().email('Invalid email').optional().or(z.literal(''))
        } else if (col.name === 'phone') {
          field = z.string().optional()
        } else {
          field = z.string().optional()
        }
    }
    shape[col.name] = col.nullable ? field.optional().nullable() : field
  }
  return z.object(shape)
}

function fieldLabel(name: string) {
  return name
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

export function AutoForm({
  open,
  onOpenChange,
  schema,
  defaultValues,
  onSubmit,
  mode,
  tableName,
  isLoading,
  enumOptions = {},
}: AutoFormProps) {
  const formSchema = buildZodSchema(schema)
  type FormData = z.infer<typeof formSchema>

  const editableColumns = schema.filter((col) => !col.isAutoGenerated)

  const {
    register,
    handleSubmit,
    control,
    formState: { errors, isSubmitting },
    reset,
  } = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: (defaultValues as FormData) ?? {},
  })

  const handleClose = () => {
    reset()
    onOpenChange(false)
  }

  const handleFormSubmit = async (data: FormData) => {
    // Strip empty strings → null
    const clean = Object.fromEntries(
      Object.entries(data).map(([k, v]) => [k, v === '' ? null : v])
    )
    await onSubmit(clean)
    handleClose()
  }

  const title = mode === 'create'
    ? `Add New ${fieldLabel(tableName.replace(/_/g, ' '))}`
    : `Edit ${fieldLabel(tableName.replace(/_/g, ' '))}`

  return (
    <Sheet
      open={open}
      onOpenChange={handleClose}
      title={title}
      description={mode === 'create' ? 'Fill in the details below to add a new record.' : 'Update the fields below.'}
    >
      <form onSubmit={handleSubmit(handleFormSubmit)} className="space-y-5">
        {editableColumns.map((col) => {
          const label = fieldLabel(col.name)
          const error = (errors as Record<string, { message?: string }>)[col.name]?.message
          const opts = enumOptions[col.name]

          if (col.type === 'boolean') {
            return (
              <div key={col.name} className="flex items-center justify-between rounded-xl border border-slate-200 p-4">
                <div>
                  <p className="text-sm font-medium text-slate-700">{label}</p>
                  <p className="text-xs text-slate-400">Toggle on or off</p>
                </div>
                <Controller
                  name={col.name as keyof FormData}
                  control={control}
                  render={({ field }) => (
                    <Switch
                      checked={!!field.value}
                      onCheckedChange={field.onChange}
                    />
                  )}
                />
              </div>
            )
          }

          if (opts) {
            return (
              <div key={col.name} className="space-y-1.5">
                <label className="block text-sm font-medium text-slate-700">{label}</label>
                <Controller
                  name={col.name as keyof FormData}
                  control={control}
                  render={({ field }) => (
                    <Select
                      value={field.value as string | undefined}
                      onValueChange={field.onChange}
                    >
                      <SelectTrigger id={`field-${col.name}`}>
                        <SelectValue placeholder={`Select ${label}`} />
                      </SelectTrigger>
                      <SelectContent>
                        {opts.map((opt) => (
                          <SelectItem key={opt} value={opt}>
                            {opt}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  )}
                />
                {error && <p className="text-xs text-red-500">{error}</p>}
              </div>
            )
          }

          const inputType =
            col.type === 'number' ? 'number' :
            col.type === 'date' ? 'date' :
            col.type === 'datetime' ? 'datetime-local' :
            col.name === 'email' ? 'email' :
            col.name === 'phone' ? 'tel' :
            'text'

          return (
            <div key={col.name} className="space-y-1.5">
              <label htmlFor={`field-${col.name}`} className="block text-sm font-medium text-slate-700">
                {label}
                {col.nullable && <span className="ml-1 text-xs text-slate-400">(optional)</span>}
              </label>
              {col.type === 'uuid' && col.name !== 'id' ? (
                <div className="space-y-1">
                  <input
                    id={`field-${col.name}`}
                    type="text"
                    placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                    {...register(col.name as keyof FormData)}
                    className={cn(
                      'w-full rounded-xl border px-3 py-2 text-sm outline-none transition-all focus:ring-2 focus:ring-blue-500/30',
                      error ? 'border-red-400' : 'border-slate-200 focus:border-blue-400'
                    )}
                  />
                  <p className="text-xs text-slate-400">UUID format required</p>
                </div>
              ) : (
                <input
                  id={`field-${col.name}`}
                  type={inputType}
                  step={col.type === 'number' ? 'any' : undefined}
                  {...register(col.name as keyof FormData)}
                  className={cn(
                    'w-full rounded-xl border px-3 py-2 text-sm outline-none transition-all focus:ring-2 focus:ring-blue-500/30',
                    error ? 'border-red-400' : 'border-slate-200 focus:border-blue-400'
                  )}
                />
              )}
              {error && <p className="text-xs text-red-500">{error}</p>}
            </div>
          )
        })}

        {/* Actions */}
        <div className="flex gap-3 pt-2">
          <button
            type="button"
            onClick={handleClose}
            className="flex-1 rounded-xl border border-slate-200 py-2.5 text-sm font-medium text-slate-600 transition-colors hover:bg-slate-50"
          >
            Cancel
          </button>
          <button
            id="autoform-submit"
            type="submit"
            disabled={isSubmitting || isLoading}
            className="flex-1 rounded-xl bg-blue-600 py-2.5 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-blue-500 disabled:opacity-60"
          >
            {isSubmitting || isLoading ? 'Saving…' : mode === 'create' ? 'Create' : 'Save Changes'}
          </button>
        </div>
      </form>
    </Sheet>
  )
}
